name: gradle_with_jacoco.yml

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: gradle test

      - name: Test coverage verification
        run: gradle jacocoTestCoverageVerification

      - name: Build
        run: gradle build